/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

<<<<<<< HEAD
#ifdef YY_USE_CONST
=======
#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
>>>>>>> 53b9ac5cdafaf08d19719e47a5de08f5bea17b7e
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

<<<<<<< HEAD
extern int yyleng;
=======
extern yy_size_t yyleng;

>>>>>>> 53b9ac5cdafaf08d19719e47a5de08f5bea17b7e
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
<<<<<<< HEAD

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

=======
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                yy_size_t yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
>>>>>>> 53b9ac5cdafaf08d19719e47a5de08f5bea17b7e
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
<<<<<<< HEAD

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;
=======
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;
>>>>>>> 53b9ac5cdafaf08d19719e47a5de08f5bea17b7e

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

<<<<<<< HEAD
YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));
=======
YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, yy_size_t len  );
>>>>>>> 53b9ac5cdafaf08d19719e47a5de08f5bea17b7e

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
<<<<<<< HEAD
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
=======
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
>>>>>>> 53b9ac5cdafaf08d19719e47a5de08f5bea17b7e
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 90
#define YY_END_OF_BUFFER 91
static yyconst short int yy_acclist[507] =
    {   0,
       24,   24,   91,   89,   90,   88,   89,   90,   88,   90,
       60,   89,   90,   11,   89,   90,   89,   90,   64,   89,
       90,   67,   89,   90,   89,   90,   82,   89,   90,   83,
       89,   90,   62,   89,   90,   56,   89,   90,   86,   89,
       90,   57,   89,   90,   63,   89,   90,   18,   89,   90,
       19,   89,   90,   79,   89,   90,   87,   89,   90,   73,
       89,   90,   71,   89,   90,   72,   89,   90,   78,   89,
       90,   54,   89,   90,   80,   89,   90,   81,   89,   90,
       68,   89,   90,   54,   89,   90,   54,   89,   90,   54,
       89,   90,   54,   89,   90,   54,   89,   90,   54,   89,

       90,   54,   89,   90,   54,   89,   90,   54,   89,   90,
       54,   89,   90,   54,   89,   90,   54,   89,   90,   54,
       89,   90,   54,   89,   90,   84,   89,   90,   69,   89,
       90,   85,   89,   90,   61,   89,   90,    6,   90,    8,
       90,    5,   90,    7,   90,   52,   89,   90,   46,   52,
       88,   89,   90,   46,   88,   90,   52,   60,   89,   90,
       11,   52,   89,   90,   52,   89,   90,   31,   52,   64,
       89,   90,   34,   52,   67,   89,   90,   52,   89,   90,
       52,   82,   89,   90,   47,   52,   83,   89,   90,   29,
       52,   62,   89,   90,   27,   52,   56,   89,   90,   49,

       52,   86,   89,   90,   28,   52,   57,   89,   90,   52,
       89,   90,   30,   52,   63,   89,   90,   18,   52,   89,
       90,   19,   52,   89,   90,   50,   52,   79,   89,   90,
       51,   52,   87,   89,   90,   40,   52,   73,   89,   90,
       38,   52,   71,   89,   90,   39,   52,   72,   89,   90,
       45,   52,   78,   89,   90,   52,   54,   89,   90,   52,
       54,   89,   90,   23,   52,   54,   89,   90,   24,   52,
       54,   89,   90,   24,   52,   54,   89,   90,   52,   80,
       89,   90,   52,   81,   89,   90,   35,   52,   68,   89,
       90,   52,   54,   89,   90,   52,   54,   89,   90,   52,

       54,   89,   90,   52,   54,   89,   90,   23,   52,   54,
       89,   90,   52,   54,   89,   90,   24,   52,   54,   89,
       90,   52,   54,   89,   90,   52,   54,   89,   90,   52,
       54,   89,   90,   52,   54,   89,   90,   24,   52,   54,
       89,   90,   52,   54,   89,   90,   52,   54,   89,   90,
       52,   84,   89,   90,   36,   52,   69,   89,   90,   48,
       52,   85,   89,   90,   52,   61,   89,   90,   88,   77,
       11,   10,   55,   58,   59,    2,    1,   16,   19,   66,
       75,   76,   74,   65,   53,   54,   54,   54,   54,   54,
       54,   54,   54,   14,   54,   54,   54,   54,   54,   54,

       54,   54,   54,   54,   54,   54,   70,    6,    5,    4,
        3,   46,   88,   44,   77,   26,   55,   22,   33,   66,
       42,   75,   43,   76,   41,   74,   32,   65,   25,   54,
       24,   54,   24,   54,   37,   70,   12,   12,    1,   16,
       16,   15,   17,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   22,
       21,   25,   25,   54,   13,   12,   13,   16,   15,   15,
       17,   17,   54,   54,   54,   54,   14,   54,   54,   54,
       54,   54,   54,   54,   54,   20,   21,   21,   25,   15,
       17,   54,   54,   54,   54,   54,   54,   54,   20,   21,

       54,   54,   54,   54,   54,    9
    } ;

static yyconst short int yy_accept[260] =
    {   0,
        1,    1,    1,    1,    1,    2,    3,    4,    6,    9,
       11,   14,   17,   19,   22,   25,   27,   30,   33,   36,
       39,   42,   45,   48,   51,   54,   57,   60,   63,   66,
       69,   72,   75,   78,   81,   84,   87,   90,   93,   96,
       99,  102,  105,  108,  111,  114,  117,  120,  123,  126,
      129,  132,  135,  138,  140,  142,  144,  146,  149,  154,
      157,  161,  165,  168,  173,  178,  181,  185,  190,  195,
      200,  205,  210,  213,  218,  222,  226,  231,  236,  241,
      246,  251,  256,  260,  264,  269,  274,  279,  283,  287,
      292,  296,  300,  304,  308,  313,  317,  322,  326,  330,

      334,  338,  343,  347,  351,  355,  360,  365,  369,  370,
      371,  372,  373,  373,  374,  374,  374,  374,  375,  376,
      377,  378,  379,  379,  379,  380,  381,  382,  383,  384,
      385,  385,  386,  387,  388,  389,  390,  391,  392,  393,
      394,  396,  397,  398,  399,  400,  401,  402,  403,  404,
      405,  406,  407,  408,  409,  410,  411,  412,  414,  416,
      418,  419,  419,  421,  423,  425,  427,  429,  429,  431,
      433,  435,  437,  437,  437,  438,  438,  438,  438,  439,
      440,  441,  442,  443,  444,  445,  446,  447,  448,  449,
      450,  451,  452,  453,  454,  455,  456,  457,  458,  459,

      460,  460,  461,  461,  462,  463,  465,  465,  466,  466,
      466,  468,  469,  470,  471,  472,  473,  474,  475,  476,
      477,  479,  480,  481,  482,  483,  484,  485,  486,  486,
      488,  489,  490,  490,  491,  492,  493,  494,  495,  496,
      497,  498,  499,  501,  501,  502,  503,  504,  504,  505,
      506,  506,  506,  506,  506,  506,  506,  507,  507
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       21,   21,   21,   21,   21,   22,   22,   23,   24,   25,
       26,   27,   28,    1,   29,   30,   29,   29,   31,   32,
       33,   33,   33,   33,   33,   34,   33,   33,   33,   33,
       33,   33,   33,   33,   35,   33,   33,   36,   33,   33,
       37,   38,   39,   40,   41,    1,   42,   43,   44,   45,

       46,   47,   48,   49,   50,   33,   51,   52,   53,   54,
       55,   56,   33,   57,   58,   59,   60,   61,   62,   36,
       63,   33,   64,   65,   66,   67,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[68] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    1,    1,    1,
        3,    1,    4,    1,    1,    1,    1,    4,    5,    5,
        5,    5,    1,    1,    1,    1,    1,    1,    6,    6,
        6,    6,    7,    7,    7,    7,    1,    1,    1,    1,
        3,    6,    6,    6,    6,    6,    6,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[271] =
    {   0,
        0,    0,   65,   66,   84,    0,  558,  763,   68,   71,
      528,  547,  473,  763,  511,  142,  763,  763,  763,  497,
      763,  473,   63,  134,  137,  763,  763,  135,  457,  136,
      763,  161,  763,  763,  763,  162,  163,  165,  164,  174,
      177,  175,  179,  187,  178,  183,  188,  189,  191,  763,
      409,  763,  763,    0,  763,   64,  447,  763,  201,  204,
      431,  429,  384,  763,  420,  187,  763,  763,  763,  410,
      763,  402,  228,  183,  215,  233,  763,  763,  184,  378,
      187,  763,  211,  256,  228,  252,  253,  763,  763,  763,
      257,  258,  262,  350,  277,  279,  285,  280,  281,  289,

      290,  291,  295,  305,  763,  320,  763,  763,  308,  763,
      377,  763,  318,  763,  347,  342,  352,  763,  763,  763,
        0,  340,  260,    0,  344,  763,  763,  763,  763,  763,
      304,  763,  317,  330,  331,  366,  319,  320,  376,  340,
      345,  377,  378,  380,  382,  392,  394,  397,  403,  406,
      408,  411,  763,    0,  225,  763,  763,  365,  763,  763,
      406,  429,  763,  763,  763,  763,  763,  446,  430,  412,
      429,  763,  303,  336,  763,  310,  293,  288,  287,    0,
      189,  284,  436,  438,  465,  471,  474,  475,  476,  488,
      489,  480,  490,  491,  493,  499,  505,  502,  501,  504,

      505,  763,  519,  523,  541,  525,  230,  763,  261,  255,
      763,  763,  387,  480,  483,  497,  553,  561,  563,  564,
      565,  567,  573,  575,  576,  581,  579,  585,  578,  586,
      763,  763,  157,  763,  763,  590,  591,  599,  605,  608,
      618,  624,  763,  166,  630,  632,  634,  138,  635,  638,
      648,  651,    0,  154,   31,  641,  763,  763,  690,  697,
      704,  709,  716,  723,  730,  737,  740,  746,  753,  755
    } ;

static yyconst short int yy_def[271] =
    {   0,
      258,    1,  259,  259,  258,    5,  258,  258,  258,  258,
      258,  260,  258,  258,  258,  261,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  262,  258,  258,  258,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  258,
      258,  258,  258,  263,  258,  258,  258,  258,  258,  258,
      258,  260,  258,  258,  258,  261,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  262,  262,  262,  262,  262,  258,  258,  258,
      262,  262,  262,   84,  262,  262,  262,  262,  262,  262,

      262,  262,  262,  262,  258,  258,  258,  258,  258,  258,
      260,  258,  258,  258,  264,  258,  265,  258,  258,  258,
      266,  258,  258,  267,  258,  258,  258,  258,  258,  258,
      258,  258,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  258,  263,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,   84,  262,
      262,  258,  258,  264,  258,  268,  269,  264,  258,  266,
      258,  258,  258,  267,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,

      258,  258,  258,  258,  258,  262,  258,  258,  268,  269,
      258,  258,  258,  258,  258,  258,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  258,  258,
      258,  258,  258,  258,  258,  262,  262,  262,  262,  262,
      262,  262,  258,  258,  262,  262,  262,  258,  262,  262,
      258,  258,  270,  270,  258,  258,  258,    0,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258
    } ;

static yyconst short int yy_nxt[831] =
    {   0,
        8,    9,   10,    9,   11,   12,   13,   14,   15,   16,
       17,   18,   19,   20,   21,   22,    8,   23,   24,   25,
       25,   25,   26,   27,   28,   29,   30,   31,   32,   32,
       32,   32,   32,   32,   32,   32,   33,    8,   34,   35,
       32,   32,   36,   37,   38,   39,   40,   32,   32,   41,
       32,   42,   43,   32,   32,   32,   44,   45,   46,   47,
       48,   49,   32,   50,   51,   52,   53,   55,   55,  109,
      109,  109,  109,  109,  109,  120,  155,   56,   56,  256,
      121,  156,   57,   57,   58,   59,   60,   59,   61,   62,
       63,   64,   65,   66,   67,   68,   69,   70,   71,   72,

       73,   74,   75,   76,   76,   76,   77,   78,   79,   80,
       81,   82,   83,   83,   84,   85,   83,   86,   87,   83,
       88,   58,   89,   90,   83,   83,   91,   92,   93,   94,
       95,   83,   83,   96,   83,   97,   98,   83,   83,   83,
       99,  100,  101,  102,  103,  104,   83,  105,  106,  107,
      108,  116,  122,  122,  122,  125,  125,  125,  125,  126,
      127,  129,  130,  123,  131,  131,  131,  131,  131,  124,
      255,  132,  132,  132,  132,  132,  123,  131,  131,  117,
      131,  131,  131,  251,  132,  132,  131,  132,  132,  132,
      131,  131,  131,  132,  131,  120,  116,  132,  132,  132,

      121,  132,  158,  158,  158,  158,  158,  158,  163,  164,
      248,  135,  166,  167,  131,  138,  244,  136,  134,  137,
      144,  132,  212,  141,  117,  139,  146,  147,  140,  143,
      142,  131,  145,  122,  122,  122,  148,  155,  132,  152,
      212,  150,  156,  151,  123,  149,  161,  161,  161,  161,
      124,  125,  125,  125,  125,  131,  131,  123,  162,  131,
      131,  131,  132,  132,  208,  131,  132,  132,  132,  168,
      208,  168,  132,  162,  169,  169,  169,  169,  183,  183,
      131,  233,  131,  131,  131,  170,  171,  132,  131,  132,
      132,  132,  131,  131,  131,  132,  175,  211,  131,  132,

      132,  132,  208,  170,  171,  132,  135,  131,  131,  109,
      109,  109,  136,  134,  132,  132,  137,  181,  170,  208,
      131,  144,  131,  131,  171,  141,  145,  132,  139,  132,
      132,  140,  142,  131,  131,  181,  170,  146,  147,  143,
      132,  132,  171,  131,  150,  208,  207,  148,  131,  151,
      132,  175,  149,  152,  177,  132,  175,  178,  122,  122,
      122,  179,  125,  125,  125,  125,  158,  158,  158,  131,
      178,  173,  186,  181,  182,  185,  132,  189,  188,  131,
      131,  131,  112,  131,  172,  131,  132,  132,  132,  178,
      132,  181,  132,  178,  178,  131,  141,  131,  178,  182,

      131,  138,  132,  165,  132,  178,  131,  132,  178,  131,
      178,  131,  178,  132,  131,  131,  132,  119,  132,  187,
      234,  132,  132,  118,  161,  161,  161,  161,  160,  192,
      190,  191,  131,  113,  112,  141,  201,  202,  234,  132,
      193,  195,  203,  258,  203,  258,  194,  204,  204,  204,
      204,  201,  202,  196,  183,  183,  159,  199,  197,  157,
      200,  206,  170,  198,  205,  205,  205,  205,  131,  213,
      214,  215,  216,  153,  131,  132,  206,  131,  131,  131,
      170,  132,  128,  131,  132,  132,  132,  213,  119,  215,
      132,  131,  131,  131,  131,  214,  131,  216,  132,  132,

      132,  132,  131,  132,  131,  131,  217,  131,  131,  132,
      118,  132,  132,  213,  132,  132,  235,  219,  229,  114,
      229,  141,  113,  230,  230,  230,  230,  141,  131,  220,
      215,  213,  218,  221,  235,  132,  141,  204,  204,  204,
      204,  204,  204,  204,  204,  141,  224,  223,  215,  222,
      226,  227,  112,  110,  231,  228,  131,  258,  225,  205,
      205,  205,  205,  132,  131,  258,  131,  131,  131,  231,
      131,  132,  232,  132,  132,  132,  131,  132,  131,  131,
      258,  258,  131,  132,  131,  132,  132,  232,  131,  132,
      258,  132,  258,  131,  131,  132,  230,  230,  230,  230,

      132,  132,  131,  141,  230,  230,  230,  230,  131,  132,
      236,  131,  258,  258,  237,  132,  258,  243,  132,  240,
      239,  131,  141,  238,  258,  241,  242,  131,  132,  258,
      141,  141,  243,  131,  132,  131,  141,  131,  131,  258,
      132,  131,  132,  245,  132,  132,  257,  258,  132,  141,
      258,  252,  141,  253,  252,  258,  253,  258,  257,  258,
      258,  258,  258,  246,  258,  253,  141,  257,  253,  258,
      258,  258,  253,  258,  258,  253,  258,  247,  141,  250,
      141,  258,  141,  258,  258,  258,  258,  258,  258,  249,
       54,   54,   54,   54,   54,   54,   54,  111,  258,  111,

      111,  111,  111,  111,  115,  258,  115,  115,  115,  115,
      115,  133,  258,  133,  133,  133,  154,  258,  154,  258,
      154,  154,  154,  174,  258,  174,  174,  174,  174,  174,
      176,  176,  176,  176,  176,  176,  176,  180,  258,  180,
      180,  180,  180,  180,  184,  184,  209,  258,  209,  209,
      209,  209,  209,  210,  258,  210,  210,  210,  210,  210,
      254,  254,    7,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,

      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258
    } ;

static yyconst short int yy_chk[831] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    4,    9,
        9,    9,   10,   10,   10,   23,   56,    3,    4,  255,
       23,   56,    3,    4,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,

        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,   16,   24,   24,   24,   25,   25,   25,   25,   28,
       28,   30,   30,   24,   32,   36,   37,   39,   38,   24,
      254,   32,   36,   37,   39,   38,   24,   40,   42,   16,
       41,   45,   43,  248,   40,   42,   46,   41,   45,   43,
       44,   47,   48,   46,   49,   74,   66,   44,   47,   48,

       74,   49,   59,   59,   59,   60,   60,   60,   79,   79,
      244,   37,   81,   81,   83,   39,  233,   37,   36,   38,
       43,   83,  181,   41,   66,   40,   45,   45,   40,   42,
       41,   85,   44,   75,   75,   75,   45,  155,   85,   49,
      181,   47,  155,   48,   75,   46,   73,   73,   73,   73,
       75,   76,   76,   76,   76,   86,   87,   75,   73,   84,
       91,   92,   86,   87,  210,   93,   84,   91,   92,   84,
      209,   84,   93,   73,   84,   84,   84,   84,  123,  123,
       95,  207,   96,   98,   99,   86,   87,   95,   97,   96,
       98,   99,  100,  101,  102,   97,  179,  178,  103,  100,

      101,  102,  177,   86,   87,  103,   92,  131,  104,  109,
      109,  109,   92,   91,  131,  104,   93,  182,   97,  176,
      133,   98,  137,  138,  102,   96,   99,  133,   95,  137,
      138,   95,   96,  134,  135,  182,   97,  100,  100,   97,
      134,  135,  102,  140,  102,  174,  173,  100,  141,  103,
      140,  116,  101,  104,  117,  141,  115,  117,  122,  122,
      122,  117,  125,  125,  125,  125,  158,  158,  158,  136,
      117,  113,  135,  122,  122,  134,  136,  138,  137,  139,
      142,  143,  111,  144,  106,  145,  139,  142,  143,  117,
      144,  122,  145,  117,  117,  146,  140,  147,  117,  122,

      148,   94,  146,   80,  147,  117,  149,  148,  117,  150,
      117,  151,  117,  149,  152,  170,  150,   72,  151,  136,
      213,  152,  170,   70,  161,  161,  161,  161,   65,  144,
      139,  143,  171,   63,   62,  142,  161,  161,  213,  171,
      145,  147,  162,  169,  162,  169,  146,  162,  162,  162,
      162,  161,  161,  148,  183,  183,   61,  151,  149,   57,
      152,  169,  171,  150,  168,  168,  168,  168,  185,  183,
      183,  184,  184,   51,  186,  185,  169,  187,  188,  189,
      171,  186,   29,  192,  187,  188,  189,  183,   22,  184,
      192,  190,  191,  193,  194,  183,  195,  184,  190,  191,

      193,  194,  196,  195,  199,  198,  185,  200,  197,  196,
       20,  199,  198,  214,  200,  197,  215,  188,  201,   15,
      201,  189,   13,  201,  201,  201,  201,  186,  206,  190,
      216,  214,  187,  192,  215,  206,  191,  203,  203,  203,
      203,  204,  204,  204,  204,  199,  195,  194,  216,  193,
      197,  198,   12,   11,  204,  200,  217,    7,  196,  205,
      205,  205,  205,  217,  218,    0,  219,  220,  221,  204,
      222,  218,  205,  219,  220,  221,  223,  222,  224,  225,
        0,    0,  227,  223,  226,  224,  225,  205,  228,  227,
        0,  226,    0,  236,  237,  228,  229,  229,  229,  229,

      236,  237,  238,  217,  230,  230,  230,  230,  239,  238,
      218,  240,    0,    0,  219,  239,    0,  230,  240,  225,
      224,  241,  220,  222,    0,  226,  227,  242,  241,    0,
      228,  223,  230,  245,  242,  246,  237,  247,  249,    0,
      245,  250,  246,  236,  247,  249,  256,    0,  250,  239,
        0,  251,  238,  251,  252,    0,  252,    0,  256,    0,
        0,    0,    0,  241,    0,  251,  240,  256,  252,    0,
        0,    0,  251,    0,    0,  252,    0,  242,  246,  247,
      249,    0,  250,    0,    0,    0,    0,    0,    0,  245,
      259,  259,  259,  259,  259,  259,  259,  260,    0,  260,

      260,  260,  260,  260,  261,    0,  261,  261,  261,  261,
      261,  262,    0,  262,  262,  262,  263,    0,  263,    0,
      263,  263,  263,  264,    0,  264,  264,  264,  264,  264,
      265,  265,  265,  265,  265,  265,  265,  266,    0,  266,
      266,  266,  266,  266,  267,  267,  268,    0,  268,  268,
      268,  268,  268,  269,    0,  269,  269,  269,  269,  269,
      270,  270,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,

      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#define INITIAL 0
#line 3 "lexer.l"
#include <stdio.h>
<<<<<<< HEAD
#include <string.h>
#include <stdlib.h>
=======
>>>>>>> 53b9ac5cdafaf08d19719e47a5de08f5bea17b7e
#include "symbol_table.h"
#include "constant_table.h"
int cnt_ln = 1; 
FILE *output_file;
 FILE *input_file;
	int nested_count = 0;
	int check_nested = 0;
<<<<<<< HEAD
char buf[100];
int ok = 0;
symbol** symbol_table;
constant** constant_table;
/* Regular definitions */
=======
#line 633 "lex.yy.c"
/* Regular definitions */

#line 636 "lex.yy.c"

#define INITIAL 0
>>>>>>> 53b9ac5cdafaf08d19719e47a5de08f5bea17b7e
#define DFA_ML 1

#define DFA_NUM 2

<<<<<<< HEAD
#line 719 "lex.yy.c"
=======
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			yy_size_t yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );
>>>>>>> 53b9ac5cdafaf08d19719e47a5de08f5bea17b7e

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
<<<<<<< HEAD
		int c = '*', n; \
=======
		int c = '*'; \
		yy_size_t n; \
>>>>>>> 53b9ac5cdafaf08d19719e47a5de08f5bea17b7e
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 33 "lexer.l"

#line 872 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

<<<<<<< HEAD
	while ( 1 )		/* loops until end-of-file is reached */
=======
		yy_load_buffer_state(  );
		}

	{
#line 26 "lexer.l"

#line 856 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
>>>>>>> 53b9ac5cdafaf08d19719e47a5de08f5bea17b7e
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 259 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 763 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
<<<<<<< HEAD
#line 34 "lexer.l"
=======
#line 27 "lexer.l"
>>>>>>> 53b9ac5cdafaf08d19719e47a5de08f5bea17b7e
{ fprintf(output_file, "Line No. %d SINGLE LINE COMMENT - %s\n", yylineno, yytext); }
	YY_BREAK
case 2:
YY_RULE_SETUP
<<<<<<< HEAD
#line 35 "lexer.l"
=======
#line 28 "lexer.l"
>>>>>>> 53b9ac5cdafaf08d19719e47a5de08f5bea17b7e
{ BEGIN DFA_ML; }
	YY_BREAK
case 3:
YY_RULE_SETUP
<<<<<<< HEAD
#line 36 "lexer.l"
=======
#line 29 "lexer.l"
>>>>>>> 53b9ac5cdafaf08d19719e47a5de08f5bea17b7e
{ ++nested_count; check_nested = 1;}	
	YY_BREAK
case 4:
YY_RULE_SETUP
<<<<<<< HEAD
#line 37 "lexer.l"
=======
#line 30 "lexer.l"
>>>>>>> 53b9ac5cdafaf08d19719e47a5de08f5bea17b7e
{
                        if (nested_count) --nested_count;
                        else{ 
                            if(check_nested){
                                fprintf(output_file, "Line No. %d NESTED COMMENT\n", yylineno);
                                check_nested = 0;
                                ok=0;BEGIN INITIAL;
                            }
                            else{
                                fprintf(output_file, "Line No. %d MULTI LINE COMMENT\n", yylineno);
                                ok=0;BEGIN INITIAL;
                            }
                        } 
					}
	YY_BREAK
case 5:
YY_RULE_SETUP
<<<<<<< HEAD
#line 51 "lexer.l"
=======
#line 44 "lexer.l"
>>>>>>> 53b9ac5cdafaf08d19719e47a5de08f5bea17b7e
;
	YY_BREAK
case 6:
YY_RULE_SETUP
<<<<<<< HEAD
#line 52 "lexer.l"
=======
#line 45 "lexer.l"
>>>>>>> 53b9ac5cdafaf08d19719e47a5de08f5bea17b7e
;
	YY_BREAK
case 7:
YY_RULE_SETUP
<<<<<<< HEAD
#line 53 "lexer.l"
=======
#line 46 "lexer.l"
>>>>>>> 53b9ac5cdafaf08d19719e47a5de08f5bea17b7e
;
	YY_BREAK
case 8:
YY_RULE_SETUP
<<<<<<< HEAD
#line 54 "lexer.l"
;
	YY_BREAK
case YY_STATE_EOF(DFA_ML):
#line 55 "lexer.l"
=======
#line 47 "lexer.l"
;
	YY_BREAK
case YY_STATE_EOF(DFA_ML):
#line 48 "lexer.l"
>>>>>>> 53b9ac5cdafaf08d19719e47a5de08f5bea17b7e
{ fprintf(output_file, "Line No. %d ERROR: MULTI LINE COMMENT NOT CLOSED\n", yylineno); return 0;}
	YY_BREAK
case 9:
YY_RULE_SETUP
<<<<<<< HEAD
#line 56 "lexer.l"
=======
#line 49 "lexer.l"
>>>>>>> 53b9ac5cdafaf08d19719e47a5de08f5bea17b7e
{ fprintf(output_file, "Line No. %d HEADER - %s\n", yylineno, yytext);}
	YY_BREAK
case 10:
YY_RULE_SETUP
<<<<<<< HEAD
#line 57 "lexer.l"
=======
#line 50 "lexer.l"
>>>>>>> 53b9ac5cdafaf08d19719e47a5de08f5bea17b7e
{ fprintf(output_file, "Line No. %d STRING - %s\n", yylineno, yytext);}
	YY_BREAK
case 11:
YY_RULE_SETUP
<<<<<<< HEAD
#line 58 "lexer.l"
=======
#line 51 "lexer.l"
>>>>>>> 53b9ac5cdafaf08d19719e47a5de08f5bea17b7e
{ fprintf(output_file, "Line No. %d ERROR: UNCLOSED STRING - %s\n", yylineno, yytext); return 0;}
	YY_BREAK
case 12:
YY_RULE_SETUP
<<<<<<< HEAD
#line 59 "lexer.l"
=======
#line 52 "lexer.l"
>>>>>>> 53b9ac5cdafaf08d19719e47a5de08f5bea17b7e
{ fprintf(output_file, "Line No. %d CHARACTER - %s\n", yylineno, yytext);}
	YY_BREAK
case 13:
YY_RULE_SETUP
<<<<<<< HEAD
#line 60 "lexer.l"
=======
#line 53 "lexer.l"
>>>>>>> 53b9ac5cdafaf08d19719e47a5de08f5bea17b7e
{ fprintf(output_file, "Line No. %d ERROR: NOT A CHARACTER - %s\n", yylineno, yytext); return 0;}						 
	YY_BREAK
case 14:
YY_RULE_SETUP
<<<<<<< HEAD
#line 61 "lexer.l"
=======
#line 54 "lexer.l"
>>>>>>> 53b9ac5cdafaf08d19719e47a5de08f5bea17b7e
{ fprintf(output_file, "Line No. %d KEYWORD - %s\n", yylineno, yytext);}
	YY_BREAK
case 15:
YY_RULE_SETUP
<<<<<<< HEAD
#line 62 "lexer.l"
{add(constant_table, yytext, "binary constant"); fprintf(output_file, "Line No. %d Binary - %s\n", yylineno, yytext);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 63 "lexer.l"
{add(constant_table, yytext, "octal constant"); fprintf(output_file, "Line No. %d Octal - %s\n", yylineno, yytext);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 64 "lexer.l"
{add(constant_table, yytext, "hexadecimal constant"); fprintf(output_file, "Line No. %d Hexadecimal - %s\n", yylineno, yytext);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 65 "lexer.l"
{add(constant_table, yytext, "integer constant"); fprintf(output_file, "Line No. %d NUMBER - %s", yylineno, yytext); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 66 "lexer.l"
{ strcpy(buf, yytext); BEGIN DFA_NUM;fprintf(output_file, "Line No. %d NUMBER - %s", yylineno, yytext); }
=======
#line 55 "lexer.l"
{ fprintf(output_file, "Line No. %d Binary - %s\n", yylineno, yytext); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 56 "lexer.l"
{ fprintf(output_file, "Line No. %d Octal - %s\n", yylineno, yytext); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 57 "lexer.l"
{ fprintf(output_file, "Line No. %d Hexadecimal - %s\n", yylineno, yytext); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 58 "lexer.l"
{ fprintf(output_file, "Line No. %d Float - %s\n", yylineno, yytext); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 59 "lexer.l"
{ fprintf(output_file, "Line No. %d Float - %s\n", yylineno, yytext); }
>>>>>>> 53b9ac5cdafaf08d19719e47a5de08f5bea17b7e
	YY_BREAK

case 20:
YY_RULE_SETUP
<<<<<<< HEAD
#line 68 "lexer.l"
{add(constant_table, buf, "exponent/float constant");if (!ok){ok=1;fprintf(output_file, "%s\n", yytext);}  else {fprintf(output_file, "\nLine No. %d NUMBER ERROR!!!! - %s\n", yylineno, yytext); return 0;}}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 69 "lexer.l"
{add(constant_table, buf, "exponent/float constant");if (!ok){ok=1;fprintf(output_file, "%s\n", yytext);}  else {fprintf(output_file, "\nLine No. %d NUMBER ERROR!!!! - %s\n", yylineno, yytext); return 0;}}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 70 "lexer.l"
{add(constant_table, buf, "float constant");if (!ok){ok=1;fprintf(output_file, "%s\n", yytext);}else {fprintf(output_file, "\nLine No. %d NUMBER ERROR!!!! - %s\n", yylineno, yytext); return 0;}}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 71 "lexer.l"
{if (!ok){add(constant_table, buf, "float constant"); ok=1;fprintf(output_file, "%s\n", yytext);}else {fprintf(output_file, "\nLine No. %d NUMBER ERROR!!!! - %s\n", yylineno, yytext); return 0;}}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 72 "lexer.l"
{add(constant_table, buf, "unsigned/long integer_constant");if (!ok){ok=1;fprintf(output_file, "%s\n", yytext);}else {fprintf(output_file, "\nLine No. %d NUMBER ERROR!!!! - %s\n", yylineno, yytext); return 0;}}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 73 "lexer.l"
{if (!ok){ok=1;fprintf(output_file, "%s\n", yytext);}else {fprintf(output_file, "\nLine No. %d NUMBER ERROR!!!! - %s\n", yylineno, yytext); return 0;}}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 74 "lexer.l"
{add(constant_table, buf, "integer constant"); if (!ok)fprintf(output_file, "\n"); fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno,yytext); ok=0;BEGIN INITIAL;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 75 "lexer.l"
{add(constant_table, buf, "integer constant"); if (!ok)fprintf(output_file, "\n"); fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno,yytext); ok=0;BEGIN INITIAL;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 76 "lexer.l"
{add(constant_table, buf, "integer constant"); if (!ok)fprintf(output_file, "\n"); fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno,yytext); ok=0;BEGIN INITIAL;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 77 "lexer.l"
{add(constant_table, buf, "integer constant"); if (!ok)fprintf(output_file, "\n"); fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno,yytext); ok=0;BEGIN INITIAL;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 78 "lexer.l"
{add(constant_table, buf, "integer constant"); if (!ok)fprintf(output_file, "\n"); fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno,yytext); ok=0;BEGIN INITIAL;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 79 "lexer.l"
{add(constant_table, buf, "integer constant"); if (!ok)fprintf(output_file, "\n"); fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno,yytext); ok=0;BEGIN INITIAL;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 80 "lexer.l"
{add(constant_table, buf, "integer constant"); if (!ok)fprintf(output_file, "\n"); fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno,yytext); ok=0;BEGIN INITIAL;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 81 "lexer.l"
{add(constant_table, buf, "integer constant"); if (!ok)fprintf(output_file, "\n"); fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno,yytext); ok=0;BEGIN INITIAL;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 82 "lexer.l"
{add(constant_table, buf, "integer constant"); if (!ok)fprintf(output_file, "\n"); fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno,yytext); ok=0;BEGIN INITIAL;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 83 "lexer.l"
{add(constant_table, buf, "integer constant"); if (!ok)fprintf(output_file, "\n"); fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno,yytext); ok=0;BEGIN INITIAL;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 84 "lexer.l"
{add(constant_table, buf, "integer constant"); if (!ok)fprintf(output_file, "\n"); fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno,yytext); ok=0;BEGIN INITIAL;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 85 "lexer.l"
{ add(constant_table, buf, "integer constant");if (!ok)fprintf(output_file, "\n"); fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno,yytext); ok=0;BEGIN INITIAL;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 86 "lexer.l"
{add(constant_table, buf, "integer constant"); if (!ok)fprintf(output_file, "\n"); fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno,yytext); ok=0;BEGIN INITIAL;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 87 "lexer.l"
{add(constant_table, buf, "integer constant"); if (!ok)fprintf(output_file, "\n"); fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno,yytext); ok=0;BEGIN INITIAL;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 88 "lexer.l"
{add(constant_table, buf, "integer constant"); if (!ok)fprintf(output_file, "\n"); fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno,yytext); ok=0;BEGIN INITIAL;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 89 "lexer.l"
{add(constant_table, buf, "integer constant"); if (!ok)fprintf(output_file, "\n"); fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno,yytext); ok=0;BEGIN INITIAL;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 90 "lexer.l"
{add(constant_table, buf, "integer constant"); if (!ok)fprintf(output_file, "\n"); fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno,yytext); ok=0;BEGIN INITIAL;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 91 "lexer.l"
{add(constant_table, buf, "integer constant"); if (!ok)fprintf(output_file, "\n"); fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno,yytext); ok=0;BEGIN INITIAL;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 92 "lexer.l"
{add(constant_table, buf, "integer constant"); if (!ok)fprintf(output_file, "\n"); fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno,yytext); ok=0;BEGIN INITIAL;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 93 "lexer.l"
{add(constant_table, buf, "integer constant"); if (!ok)fprintf(output_file, "\n"); fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno,yytext); ok=0;BEGIN INITIAL;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 94 "lexer.l"
{add(constant_table, buf, "integer constant"); if (!ok)fprintf(output_file, "\n");ok=0;BEGIN INITIAL;} 
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 95 "lexer.l"
{add(constant_table, buf, "integer constant"); if (!ok)fprintf(output_file, "\n"); fprintf(output_file,"Line No. %d RIGHT PARENTHESIS - %s\n", yylineno, yytext); ok=0;BEGIN INITIAL;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 96 "lexer.l"
{add(constant_table, buf, "integer constant"); if (!ok)fprintf(output_file, "\n"); fprintf(output_file,"Line No. %d RIGHT BRACE - %s\n", yylineno, yytext); ok=0;BEGIN INITIAL;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 97 "lexer.l"
{add(constant_table, buf, "integer constant"); if (!ok)fprintf(output_file, "\n"); fprintf(output_file,"Line No. %d COMMA - %s\n", yylineno, yytext); ok=0;BEGIN INITIAL;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 98 "lexer.l"
{add(constant_table, buf, "integer constant"); if (!ok)fprintf(output_file, "\n"); fprintf(output_file,"Line No. %d COMMA - %s\n", yylineno, yytext); ok=0;BEGIN INITIAL;}
=======
#line 60 "lexer.l"
{ fprintf(output_file, "Line No. %d Float - %s\n", yylineno, yytext); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 61 "lexer.l"
{ fprintf(output_file, "Line No. %d Integer - %s\n", yylineno, yytext); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 62 "lexer.l"
{ fprintf(output_file, "Line No. %d Integer - %s\n", yylineno, yytext); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 63 "lexer.l"
{ fprintf(output_file, "Line No. %d Integer - %s\n", yylineno, yytext); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 64 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno, yytext);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 65 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno, yytext); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 66 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno, yytext); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 67 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno, yytext); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 68 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno, yytext); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 69 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno, yytext); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 70 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno, yytext); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 71 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno, yytext); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 72 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno, yytext); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 73 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno, yytext); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 74 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno, yytext); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 75 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno, yytext); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 76 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno, yytext); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 77 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno, yytext); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 78 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno, yytext); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 79 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno, yytext); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 80 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno, yytext); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 81 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno, yytext); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 82 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno, yytext); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 83 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno, yytext); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 84 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno, yytext); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 85 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno, yytext); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 86 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno, yytext); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 87 "lexer.l"
{ fprintf(output_file, "Line No. %d FUNCTION - %s\n", yylineno, yytext);}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 88 "lexer.l"
{ fprintf(output_file, "Line No. %d IDENTIFIER - %s\n", yylineno, yytext);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 89 "lexer.l"
{ fprintf(output_file, "Line No. %d INTEGER - %s\n", yylineno, yytext);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 90 "lexer.l"
{ fprintf(output_file, "Line No. %d FLOATING POINT - %s\n", yylineno, yytext);}
>>>>>>> 53b9ac5cdafaf08d19719e47a5de08f5bea17b7e
	YY_BREAK
case 51:
YY_RULE_SETUP
<<<<<<< HEAD
#line 99 "lexer.l"
{add(constant_table, buf, "integer constant"); if (!ok)fprintf(output_file, "\n"); fprintf(output_file,"Line No. %d SEMICOLON - %s\n", yylineno, yytext); ok=0;BEGIN INITIAL; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 100 "lexer.l"
{ fprintf(output_file, "\nLine No. %d NUMBER ERROR!!!! - %s\n", yylineno, yytext); return 0;}
=======
#line 91 "lexer.l"
; 
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 92 "lexer.l"
{ fprintf(output_file,"Line No. %d LEFT BRACKET - %s\n", yylineno, yytext); }
>>>>>>> 53b9ac5cdafaf08d19719e47a5de08f5bea17b7e
	YY_BREAK

case 53:
YY_RULE_SETUP
<<<<<<< HEAD
#line 102 "lexer.l"
{sym_add(symbol_table, yytext, yylineno, "function"); fprintf(output_file, "Line No. %d FUNCTION - %s\n", yylineno, yytext);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 103 "lexer.l"
{sym_add(symbol_table, yytext, yylineno, "identifier"); fprintf(output_file, "Line No. %d IDENTIFIER - %s\n", yylineno, yytext);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 104 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno,yytext);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 105 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno,yytext); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 106 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno,yytext); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 107 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno,yytext); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 108 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno,yytext); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 109 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno,yytext); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 110 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno,yytext); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 111 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno,yytext); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 112 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno,yytext); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 113 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno,yytext); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 114 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno,yytext); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 115 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno,yytext); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 116 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno,yytext); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 117 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno,yytext); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 118 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno,yytext); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 119 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno,yytext); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 120 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno,yytext); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 121 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno,yytext); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 122 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno,yytext); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 123 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno,yytext); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 124 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno,yytext); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 125 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno,yytext); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 126 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno,yytext); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 127 "lexer.l"
{ fprintf(output_file, "Line No. %d OPERATOR - %s\n", yylineno,yytext); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 128 "lexer.l"
{ fprintf(output_file,"Line No. %d COMMA - %s\n", yylineno, yytext); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 129 "lexer.l"
{ fprintf(output_file,"Line No. %d LEFT BRACKET - %s\n", yylineno, yytext); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 130 "lexer.l"
{ fprintf(output_file,"Line No. %d RIGHT BRACKET - %s\n", yylineno, yytext); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 131 "lexer.l"
{ fprintf(output_file,"Line No. %d LEFT PARENTHESIS - %s\n", yylineno, yytext); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 132 "lexer.l"
{ fprintf(output_file,"Line No. %d RIGHT PARENTHESIS - %s\n", yylineno, yytext); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 133 "lexer.l"
{ fprintf(output_file,"Line No. %d LEFT BRACE - %s\n", yylineno, yytext); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 134 "lexer.l"
{ fprintf(output_file,"Line No. %d RIGHT BRACE - %s\n", yylineno, yytext); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 135 "lexer.l"
{ fprintf(output_file,"Line No. %d COMMA - %s\n", yylineno, yytext); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 136 "lexer.l"
{ fprintf(output_file,"Line No. %d SEMICOLON - %s\n", yylineno, yytext); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 137 "lexer.l"
; 
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 138 "lexer.l"
=======
#line 93 "lexer.l"
{ fprintf(output_file,"Line No. %d RIGHT BRACKET - %s\n", yylineno, yytext); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 94 "lexer.l"
{ fprintf(output_file,"Line No. %d LEFT PARENTHESIS - %s\n", yylineno, yytext); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 95 "lexer.l"
{ fprintf(output_file,"Line No. %d RIGHT PARENTHESIS - %s\n", yylineno, yytext); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 96 "lexer.l"
{ fprintf(output_file,"Line No. %d LEFT BRACE - %s\n", yylineno, yytext); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 97 "lexer.l"
{ fprintf(output_file,"Line No. %d RIGHT BRACE - %s\n", yylineno, yytext); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 98 "lexer.l"
{ fprintf(output_file,"Line No. %d COMMA - %s\n", yylineno, yytext); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 99 "lexer.l"
{ fprintf(output_file,"Line No. %d SEMICOLON - %s\n", yylineno, yytext); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 100 "lexer.l"
>>>>>>> 53b9ac5cdafaf08d19719e47a5de08f5bea17b7e
{ 
    if(yytext[0] == '#')
		fprintf(output_file,"Line No. %d PREPROCESSOR ERROR - %s\n", yylineno, yytext);
	else
		fprintf(output_file,"Line No. %d ERROR ILLEGAL CHARACTER - %s\n", yylineno, yytext);
    return 0;
  }
	YY_BREAK
case 90:
YY_RULE_SETUP
<<<<<<< HEAD
#line 145 "lexer.l"
ECHO;
	YY_BREAK
#line 1438 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(DFA_NUM):
				yyterminate();
=======
#line 107 "lexer.l"
ECHO;
	YY_BREAK
#line 1254 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();
>>>>>>> 53b9ac5cdafaf08d19719e47a5de08f5bea17b7e

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
<<<<<<< HEAD
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;
=======
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;
>>>>>>> 53b9ac5cdafaf08d19719e47a5de08f5bea17b7e

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

<<<<<<< HEAD
	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;
=======
	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}
>>>>>>> 53b9ac5cdafaf08d19719e47a5de08f5bea17b7e

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 259 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 259 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 258);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
<<<<<<< HEAD
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];
=======
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];
>>>>>>> 53b9ac5cdafaf08d19719e47a5de08f5bea17b7e

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
<<<<<<< HEAD
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;
=======
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);
>>>>>>> 53b9ac5cdafaf08d19719e47a5de08f5bea17b7e

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


<<<<<<< HEAD
#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

=======
/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
>>>>>>> 53b9ac5cdafaf08d19719e47a5de08f5bea17b7e
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
<<<<<<< HEAD
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
=======
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
>>>>>>> 53b9ac5cdafaf08d19719e47a5de08f5bea17b7e
		} \
	while ( 0 )


<<<<<<< HEAD
/* Internal utility routines. */
=======
/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */
>>>>>>> 53b9ac5cdafaf08d19719e47a5de08f5bea17b7e

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

<<<<<<< HEAD
#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 145 "lexer.l"
=======
#define YYTABLES_NAME "yytables"

#line 107 "lexer.l"
>>>>>>> 53b9ac5cdafaf08d19719e47a5de08f5bea17b7e


int yywrap() {
    return 1;
}

int main(int argc, char *argv[]) {
    if (argc != 3) {
        fprintf(stderr, "Usage: %s input_file output_file\n", argv[0]);
        return 1;
    }

    input_file = fopen(argv[1], "r");
    if (!input_file) {
        perror("Error opening input file");
        return 1;
    }

    output_file = fopen(argv[2], "w");
    if (!output_file) {
        perror("Error opening output file");
        fclose(input_file);
        return 1;
    }

    yyin = input_file;
     symbol_table= symboltable();
    constant_table=constanttable();
    yylex();
   
    print_table(symbol_table);
    print_const_table(constant_table);
    fclose(input_file);
    fclose(output_file);
    return 0;
}